// <auto-generated />
using Desk.Gist.EntityFrameworkCore.WebApi.Datas;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Desk.Gist.EntityFrameworkCore.WebApi.Datas.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Desk.Gist.EntityFrameworkCore.WebApi.Datas.Entities.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("Blog url");

                    b.HasKey("Id");

                    b.ToTable("blogs", "dev");

                    b
                        .HasComment("Blogs managed on the website");
                });
#pragma warning restore 612, 618
        }
    }
}
